services:
  - type: web
    name: maxvia-stock-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 maxvia_monitor.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8692174015:AAFl7TCPswrYFHoMhSbgAtb5V3F8Px1k_HA
      - key: TELEGRAM_CHAT_ID
        value: "11579952"
      - key: MAXVIA_COOKIE
        value: "XSRF-TOKEN=eyJpdiI6Inl5Q3RsMTVPTTcvM3FTVU5Uc0lQU2c9PSIsInZhbHVlIjoiVGxrbnd6RDFQd29GU24rVFY5V000MEwvR2tsM0htU3RjVjgxaEZ2aDVsQ09YaG9mL1dBZjJOVVZDclFhY0R3ckRKR3Q5MmxyS3NmeEFTZlBGbnBlU3N0bzMxUE54WDNLRkhNVlZNbmJ5dHFOM1greVY2eGkzVnNFQmlvZHNuMHYiLCJtYWMiOiI5MjYzNDhlNDVmM2Q1ZTM5NzRiOTRhM2Q0ZTRhYmZjMThmOGRhODU1NzA4ZWEwZTE5YTRjMjY1OTNlZDg2MGMyIn0%3D; laravel_session=eyJpdiI6Inp0eEIyZ2VIUjE1d2ZuS0ZqWkM0eUE9PSIsInZhbHVlIjoiektqM0FtV096WXdCVUFUUGhVcWFKLzBtblZkRm1YNGpsaHNCNXpHV2Qzdm8wUHNwa2xoU1hNdDZTdnZmdGVPOW1BMThWblB5UmFES25XWWJ6WnNiWWwwNmxnT1cvd0FycVVmaGt3K3FjT3VoUXNWQlZRZ1psWUVnZkllK2l3M3EiLCJtYWMiOiJkZGYyZTBmMGQ3ZGM4NWQ4ZTMxZmRhNWYwMTE3ZWYyNGU2Njc5NzRkZGU1OTljODM1YmUxNmViMmM3OTY4MDEyIn0%3D"

