services:
  - type: web
    name: maxvia-stock-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 maxvia_monitor.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8692174015:AAFl7TCPswrYFHoMhSbgAtb5V3F8Px1k_HA
      - key: TELEGRAM_CHAT_ID
        value: "11579952"
